site_name: HFT Wiki
site_url: https://wiki.vikingtrading.net/
site_description: >-
  HFT Wiki：高频交易技术文档中心

# repo_name: relaxdl/hft-wiki
# repo_url: https://github.com/relaxdl/hft-wiki

# 顶部导航 / 左侧导航 的整体结构
nav:
  - Home: index.md
  - Documentation: documentation.md

theme:
  name: material
  language: en
  # logo: images/logo.svg           # 可以先不建，后面再加
  # favicon: images/favicon.png     # 同上
  icon:
    logo: material/currency-btc
    # repo: fontawesome/brands/github

  features:
    # 导航相关（顶部 Tab + 左侧多级导航 + 页面右侧小目录）
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.indexes

    # 内容体验
    - content.code.copy
    - content.tabs.link
    - content.tooltips

    # 搜索
    - search.highlight
    - search.suggest
    - search.share

  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social: []
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/relaxdl/hft-wiki
  #     name: GitHub

plugins:
  - search
  # 如果你想玩 tags（标签索引页），可以后面再打开
  # - tags:
  #     tags_file: academy/all-tags.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
