site_name: HFT技术文档中心
site_url: https://wiki.vikingtrading.net/
site_description: >-
  HFT技术文档中心: HFT技术文档中心

# repo_name: relaxdl/hft-wiki
# repo_url: https://github.com/relaxdl/hft-wiki

# 顶部导航 / 左侧导航 的整体结构
nav:
  - 主页: index.md
  - 文档: 
    - 支持的平台: common/support_platform.md
    - 数据:
      - 类型定义: common/data_type.md
      - 数据结构: common/data_structure.md
      - 常用数据结构: common/common_data_structure.md
    - 路径管理: common/path_manager.md
    - 共享内存: 
      - 基础: common/shm_basic.md
      - 路径: common/shm_path.md
      - 最佳实践: common/shm_best_practice.md
      - 资产&策略资产: common/shm_balance.md
      - 自定义信号: common/shm_custom_signal.md
    - 交易所:
      - REST API: common/exchange_rest_api.md
      - Websocket API: common/exchange_websocket_api.md
      - Websocket Stream: common/exchange_websocket_stream.md
    - 配置:
      - 静态配置: common/config_spec.md
      - 跨进程的动态配置: common/config_param.md
      - Service配置: common/config_service.md
    - 转账:
      - 统一API: common/transfer_api.md
      - 任务: common/transfer_task_manager.md
    - 网关:
      - 资产: common/gateway_balance.md
      - 订单: common/gateway_order.md
    - IPC:
      - 发布&订阅: common/ipc_pubsub.md
      - 命令: common/ipc_command.md
      
theme:
  name: material
  language: zh
  # logo: images/logo.svg           # 可以先不建，后面再加
  # favicon: images/favicon.png     # 同上
  icon:
    logo: material/currency-btc
    # repo: fontawesome/brands/github

  features:
    # 导航相关（顶部 Tab + 左侧多级导航 + 页面右侧小目录）
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.expand 菜单默认不需要展开
    - navigation.path
    - navigation.indexes
    - navigation.top

    # 内容体验
    - content.code.copy
    - content.tabs.link
    - content.tooltips

    # 目录
    - toc.follow

    # 搜索
    - search.highlight
    - search.suggest
    - search.share

    # 公告
    - announce.dismiss

  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social: []
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/relaxdl/hft-wiki
  #     name: GitHub

plugins:
  - search
  # 如果你想玩 tags（标签索引页），可以后面再打开
  # - tags:
  #     tags_file: academy/all-tags.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
